kronostechnologies/tax-ca

- package.json
- src/pension/cpp.js
- src/pension/oas.js
- src/pension/qpp.js
- yarn.lock
⚠️ TO REVIEWER ⚠️ 
Poke moi lorsque la PR sera approved, et je vais m'occuper de publish la version et d'updater `kronos-fna` et `fna-engine`.
TIPS:
Regarde juste le premier commit, tu vas voir les chiffres que j'ai changé l'autre c'est juste du lint.
> Fix update 2019 tax values

- src/misc/iqpf.js
Create new version and push to NPN please.
> Projection assumption guidelines update for 2019

- src/taxes/income-tax.ts
> Tax-ca fix wrong bracket

- src/pension/cpp.ts
Some adjustment using the latest published pension amounts.
> CPP latest 2020 update

- package.json
- src/pension/cpp.ts
- src/pension/oas.ts
- src/pension/qpp.ts
- src/pension/tests/cpp.spec.ts
- src/pension/tests/oas.spec.ts
- src/pension/tests/qpp.spec.ts
- src/utils/date.ts
- src/utils/math.ts
- src/utils/tests/date.spec.ts
- src/utils/tests/math.spec.ts
- yarn.lock
Pour faire un test complet, attendre ABF-2266.
> ABF-2313: Added OAS/CPP monthly bonus/penalty depending on request date

- src/misc/iqpf.ts
Suite à cet update, je vais faire les PR dans tous nos projets pour mettre à jour tax-ca avec la nouvelle version.
> ABF-2757: Update IQPF projections for 2020

- src/pension/old-age-security.ts
Lorsque ce sera mergé, je ferai un nouvelle version et je vais faire les bumps dans les app concernés
> ABF-3063: Update OAS repayment MIN and MAX for 2020

- src/taxes/income-tax.ts
Lien vers [TaxTips](https://www.taxtips.ca/marginaltaxrates.htm)
Lien vers [EY](https://www.ey.com/fr_ca/tax/tax-calculators)
** FYI le calculateur de TaxTips ne fonctionne pas pour les provinces avec une Surtax (Ontario et PEI)
> ABF-3413: Fix marginal rate calculation functions

- src/taxes/income-tax.ts
Valider le calcul du taux effectif
Valider le calcul simplifié des taxes.
> ABF-3346 : Simplification calcul de l'impot et ajout du taux effectif

- src/pension/old-age-security.ts
> ABF-3583: Update OAS Max Monthly Payment (Updated July 2021)

- README.md
- src/taxes/dividend-credit.ts
- src/taxes/index.ts
> ABF-3784: Add rates for dividend tax credit

- src/pension/old-age-security.ts
> ABF-3828: Update OAS values for October

- src/misc/iqpf-stats.ts
Pas trop compliqué, j'ai ajouté la statistique de taux de performance / gain de productivité aux données de l'IQPF.  C'est 1% pour 2021.
1. Link this branch of `tax-ca` in another project
- [ N/A] New features are unit tested.
> ABF-4017 feat(IQPF): Adds performance rate to IQPF statistics

- src/pension/old-age-security.ts
- src/pension/tests/old-age-security.spec.ts
C'est une fonction que j'avais mis dans la PR https://github.com/kronostechnologies/fna-engine/pull/1195 de fna-engine mais qui a plus de sens dans tax-ca (et ça va nous permettre de la tester).
> feat(OAS): Ajoute une fonction de calcul du montant de repayment

- .github/workflows/sync-renovate-jira.yml
ABF-4313
Permet de corriger la transition automatique à Done par l'action
> ABF-4313 ci(tax-ca): add jira-transition-resolve input to sync-renovate-jira action

- src/pension/old-age-security.ts
Mise à jour des montants pour la PSV octobre 2022
> October 2022 OAS update

- src/pension/old-age-security.ts
- src/pension/tests/old-age-security.spec.ts
Le naming est un peu shitteux je sais pas si vous êtes plus inspiré que moi
1. `kronos-fna` doit linker cette PR pour tester
2. `kronos-fna` sur la branch `dev/ABF-4382` pour tester
> ABF-4373: Changed OAS ratio calcs

- .github/CODEOWNERS
> docs(tax-ca): change codeowners from team-abf to plan

- .github/workflows/sync-renovate-jira.yml
Le nom de la transition a changé.
> ABF-4591 fix(tax-ca): fix resolve transition for sync-renovate-jira workflow

- src/pension/old-age-security.ts
- src/pension/tests/old-age-security.spec.ts
Description
1. Linker à la branche `dev/ABF-4646` de `kronos-fna`
Plus de détails pour reproduire l'erreur dans [la carte JIRA](https://jira.equisoft.com/browse/ABF-4597)
> [ABF-4645] Fix(OAS): updating bonus/malus application criterias

- src/investments/registered-retirement-income-fund.ts
Description
1. Liker `tax-ca` à `fna-engine` puis `fna-engine` à `kronos-fna`
> [ABF-4687] Fix(RRIF): rounding withdrawal percentage

- src/investments/life-income-fund.ts
- src/investments/registered-retirement-income-fund.ts
- src/investments/registered-retirement-savings-plan.ts
- src/investments/tax-free-savings-account.ts
- src/investments/tests/life-income-fund.spec.ts
- src/misc/consumer-price-index.ts
- src/misc/iqpf-stats.ts
- src/misc/life-expectancy.ts
- src/misc/ppp-increase-factor.ts
- src/pension/canada-pension-plan.ts
- src/pension/old-age-security.ts
- src/pension/public-pension-plan.ts
- src/pension/quebec-pension-plan.ts
- src/pension/supplemental-pension-plan.ts
- src/taxes/dividend-credit.ts
- src/taxes/employment-insurance.ts
- src/taxes/income-tax.ts
- src/taxes/quebec-parental-insurance-plan.ts
Mise a jour des valeurs tax-ca
> [dev/ABF-4698] update(values): yearly values update

- src/pension/old-age-security.ts
> [ABF-6373] Fix(OAS): update OAS monthly payment max value

- src/investments/life-income-fund.ts
- src/misc/code-types.ts
Ajout d'un constante pour nos calculs de désimobilisation du LIRA en fonction du YMPE
> ABF-6814 feat(tax-ca): Add YMPE unlocking ratio by province

- .github/renovate.json5
Description
1. Action 1
2. Action 2
> Normalize Renovate config (QCTECH-715)

- src/pension/old-age-security.ts
Description
Dans TAX-CA, mettre à jour 
- INCREASE.REPAYMENT_MAX à 148179.00
- MONTHLY_PAYMENT_MAX à 707.68
- REPAYMENT.MAX à 142609.00
Test
> [ABF-7037] update(old-age-security.ts):  october values

- src/investments/tax-free-savings-account.ts
CRITÈRES D'ACCEPTATION
--------------------------------
1. Dans Tax-ca, modifier le  UNROUNDED_MAX_CONTRIBUTION pour 6751 (pour l'année 2024)
> [ABF-7437] fix(tax-free-saving-account.ts): adjusted unrounded_max_contribution

- src/investments/life-income-fund.ts
- src/investments/tests/life-income-fund.spec.ts
> [ABF-7470] fix(lif): update maxWithdrawalpct method

- .github/workflows/build-and-deploy.yml
Il manquait le fetch de toutes les branches releases.
> ABF-7474: fix tax-ca hotfix workflow by fetching release branches

- .github/workflows/build-and-deploy.yml
> ABF-7474: fix tax-ca hotfix workflow by fetching release branches (#432)

- src/misc/iqpf-stats.ts
Description
update projection values
> [ABF-7857] dev(projection IQPF): update projection values

- src/pension/old-age-security.ts
> ABF-8223 feat(oas): Update Old Age Security Monthly Payment Max constant value

- src/pension/old-age-security.ts
> [ABF-8669] dev(PSV): updated max monthly payment value

- yarn.lock
> ABF-8855 deps(tax-ca): Fix yarn lock file

- src/investments/registered-education-savings-plan/quebec-education-savings-incentive.ts
> [ABF-9321] QUESI

- src/investments/registered-education-savings-plan/canada-learning-bond.ts
- src/investments/registered-education-savings-plan/tests/canada-learning-bond.spec.ts
> [ABF-9318] dev(CLB): Ajout CLB

- src/investments/registered-education-savings-plan/index.ts
> [ABF-9341] fix exports

- src/investments/registered-education-savings-plan/british-columbia-training-and-education-savings-grant.ts
- src/investments/registered-education-savings-plan/tests/british-columbia-training-and-education-savings-grant.spec.ts
> [ABF-9324] BCTESG

- src/investments/registered-education-savings-plan/index.ts
> [ABF-9342] fix export

- README.md
- src/misc/index.ts
- src/misc/ipf-stats.ts
- src/misc/iqpf-stats.ts
ABF-9905
- Mise à jour 2025 des projections de l'IPF (ajout de trois equitities)
- Rebranding de IQPF vers IPF.
> ABF-9905 dev(iqpf): Add two new equities and update Canadian Equities value

- src/investments/registered-education-savings-plan/income-level.ts
Description
Export enum sans const pour pouvoir l'utiliser dans d'autres projets
> [ABF-10244] fix(IncomeLevelType): Export enum sans const pour pouvoir l'utiliser dans d'autres projets

- src/pension/old-age-security.ts
> [ABF-10864] dev(PSV): Update PSV
